version: "3.8"

services:
  backend:
    build: ../backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/lexilive
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ../LexiLive
    container_name: frontend
    ports:
      - "3000:3000"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lexilive
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lexilive
    ports:
      - "10051:10051"
    depends_on:
      - database

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lexilive
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"

volumes:
  db_data:
